[workspace]
authors = ["Stuart Berg <bergs@janelia.hhmi.org>"]
channels = ["flyem-forge", "conda-forge"]
name = "ngsupport"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
flask = ">=3.1.1,<4"
flask-cors = ">=6.0.1,<7"
flask-compress = ">=1.18,<2"
gunicorn = ">=23.0.0,<24"
google-cloud-storage = ">=3.1.0,<4"
neuclease = ">=neuclease-0.8.post0.dev38"
vol2mesh = ">=0.1.post24"

[pypi-dependencies]
tensorstore = ">=0.1.76, <0.2"
neuroglancer = ">=2.40.1, <3"
